[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]

[phases.start]
cmd = "cd backend && node dist/app.js"