import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Backend',
      link: {
        type: 'doc',
        id: 'backend/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend',
        },
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      link: {
        type: 'doc',
        id: 'frontend/index', // Este archivo lo debes crear: docs/frontend/index.md
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'frontend',
        },
      ],
    },
  ],
};

export default sidebars;
