import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Backend',
      link: {
        type: 'doc',
        id: 'backend/index', // El documento que se abre al hacer clic en 'Backend'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend', // <- Esto mostrará todas las subcarpetas dentro de backend (como controllers, config, etc.)
        },
      ],
    },
  ],
};

export default sidebars;
