name: Deploy to Railway



on:

  push:

    branches:

      - main



jobs:

  deploy:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v3



      - name: Instalar Railway CLI

        run: npm install -g @railway/cli



      - name: Autenticarse en Railway

        env:

          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

        run: echo "// Autenticación automática con token"



      - name: Linkear proyecto Railway

        env:

          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

        run: railway link 8261cd1c-3419-42b6-a40f-4e1ef940ce80



      - name: Hacer deploy con Railway

        env:

          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

        run: railway up --service=producttrack --ci