name: Deploy to Railway

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: Ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v3



      - name: Install Railway CLI (nuevo)

        run: npm install -g @railway/cli



      - name: Deploy to Railway

        env:

          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

        run: railway up --service=producttrack