name: Deploy to Railway



on:

  push:

    branches:

      - main



jobs:

  deploy:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v3



      - name: Instalar Railway CLI

        run: npm install -g @railway/cli



      - name: Deploy a Railway

        env:

          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

        run: |

          railway up --service=producttrack --project=8261cd1c-3419-42b6-a40f-4e1ef940ce80